leftnav:
- identifier: 3320ee7c-9eca-4a19-ac6d-fc2fbf24f00c
  name: "Teaching La Princesse de Cl\xE8ves Website"
  pageRef: "/external-resources/teaching-la-princesse-de-cl\xE8ves-website_3320ee7c-9eca-4a19-ac6d-fc2fbf24f00c"
  weight: 10
